# Generated by Django 2.0.8 on 2019-01-16 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teacher', '0001_initial'),
        ('lesson', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('more_price', models.IntegerField(default=0, verbose_name='额外的价格')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lesson.ScheduleLessonInfo', verbose_name='课程')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.StudentInfo', verbose_name='学生')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.TeacherInfo', verbose_name='老师')),
            ],
            options={
                'verbose_name': '价格表',
                'verbose_name_plural': '价格表',
            },
        ),
    ]
