# Generated by Django 2.1.5 on 2019-01-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinfo',
            name='sliding_price',
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='student_sliding_price',
            field=models.IntegerField(default=0, verbose_name='学生变动价格'),
        ),
        migrations.AddField(
            model_name='priceinfo',
            name='teacher_sliding_price',
            field=models.IntegerField(default=0, verbose_name='老师变动价格'),
        ),
    ]
