# Generated by Django 2.1.5 on 2019-01-18 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_auto_20190118_1244'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priceinfo',
            name='teacher_sliding_price',
        ),
    ]
