# Generated by Django 2.0.8 on 2019-01-19 09:08

from django.db import migrations


def forwards_func(apps, schema_editor):
    Identity = apps.get_model("lesson", "SubjectInfo")
    db_alias = schema_editor.connection.alias
    Identity.objects.using(db_alias).bulk_create([
        Identity(name='语文', kind=1),
        Identity(name='数学', kind=1),
        Identity(name='英语', kind=1),
        Identity(name='物理', kind=1),
        Identity(name='化学', kind=1),
        Identity(name='晚辅', kind=0),
    ])


def reverse_func(apps, schema_editor):
    Identity = apps.get_model("lesson", "SubjectInfo")
    db_alias = schema_editor.connection.alias
    Identity.objects.using(db_alias).filter(name='语文', kind=1).delete()
    Identity.objects.using(db_alias).filter(name='数学', kind=1).delete()
    Identity.objects.using(db_alias).filter(name='英语', kind=1).delete()
    Identity.objects.using(db_alias).filter(name='物理', kind=1).delete()
    Identity.objects.using(db_alias).filter(name='化学', kind=1).delete()
    Identity.objects.using(db_alias).filter(name='晚辅', kind=0).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
