# Generated by Django 2.1.5 on 2019-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulelessoninfo',
            name='teacher_sliding_price',
            field=models.IntegerField(default=0, verbose_name='老师变动价格'),
        ),
    ]
